---
abstract: 'Wrap git command-line interface without blocking'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: '0.3601'
  Sort::Versions: '0'
  Test::Deep: '0'
  Test::Exception: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AnyEvent-Git-Wrapper
recommends:
  EV: '0'
requires:
  AnyEvent: '0'
  AnyEvent::Open3::Simple: '0.76'
  File::pushd: '0'
  Git::Wrapper: '0.030'
  Scalar::Util: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/plicease/anyevent-git-wrapper/issues
  homepage: http://perl.wdlabs.com/AnyEvent-Git-Wrapper/
  repository: git://github.com/plicease/anyevent-git-wrapper.git
version: '0.06'
